# Run every 10 minutes
OrdersPoster:
  cron: '*/10 * * * *'
  class: 'Workers::OrdersPoster'

ProductsPoster:
  cron: '00 0 * * *'
  class: 'Workers::ProductsPoster'

InventoryPuller:
  cron: '00 0 * * *'
  class: 'Workers::InventoryPuller'

ReturnsPuller:
  cron: '00 0 * * *'
  class: 'Workers::ReturnsPuller'

OrdersPuller:
  cron: '30 0 * * *'
  class: 'Workers::OrdersPuller'

ProductsPuller:
  cron: '00 */2 * * *'
  class: 'Workers::ProductsPuller'

