# Run every 10 minutes
OrdersPoster:
  cron: '*/10 * * * *'
  class: 'Workers::OrdersPoster'

ProductsPoster:
  cron: '00 0 * * *'
  class: 'Workers::ProductsPoster'

InventoryPuller:
  cron: '00 0 * * *'
  class: 'Workers::InventoryPuller'

OrderPuller:
  cron: '00 0 * * *'
  class: 'Workers::OrdersPuller'

